Fix compilation on MacOSX: use ::bind (socket bind) instead of std::bind
Error was:

server.cc:125:68: error: invalid operands to binary expression
('__bind<int &, sockaddr *, unsigned long>' and 'int')
    if (bind(fd, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) != 0)